[0m14:30:34.138560 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111cd7cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11348b9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11348bb10>]}


============================== 14:30:34.141102 | b2db1b61-91ed-4db7-9886-5a6f273a1374 ==============================
[0m14:30:34.141102 [info ] [MainThread]: Running with dbt=1.10.13
[0m14:30:34.141364 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'fail_fast': 'False', 'indirect_selection': 'eager', 'debug': 'False', 'use_experimental_parser': 'False', 'version_check': 'True', 'introspect': 'True', 'target_path': 'None', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'invocation_command': 'dbt init', 'use_colors': 'True', 'log_path': 'logs', 'warn_error': 'None', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'profiles_dir': '/Users/izakmohamed/.dbt', 'static_parser': 'True', 'no_print': 'None', 'empty': 'None', 'printer_width': '80', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'write_json': 'True', 'quiet': 'False'}
[0m14:30:34.151665 [info ] [MainThread]: Creating dbt configuration folder at /Users/izakmohamed/.dbt
[0m14:31:28.898024 [debug] [MainThread]: Starter project path: /Users/izakmohamed/Documents/DEV & CODE/SIMPLON 2025/Formation Intensif/BRIEF/BRIEF 08 Apache Spark/Apache_Spark/env_pyspark/lib/python3.13/site-packages/dbt/include/starter_project
[0m14:31:28.912988 [info ] [MainThread]: 
Your new dbt project "postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:31:28.913977 [info ] [MainThread]: Setting up your profile.
[0m14:34:55.808958 [info ] [MainThread]: Profile postgres written to /Users/izakmohamed/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:34:55.819373 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 261.71353, "process_in_blocks": "0", "process_kernel_time": 0.167465, "process_mem_max_rss": "105807872", "process_out_blocks": "0", "process_user_time": 0.655224}
[0m14:34:55.821878 [debug] [MainThread]: Command `dbt init` succeeded at 14:34:55.821440 after 261.72 seconds
[0m14:34:55.823858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11352b5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111dba9f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113552140>]}
[0m14:34:55.824819 [debug] [MainThread]: Flushing usage events
[0m14:34:56.326208 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:58:42.290879 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103d87cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10598b9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10598bb10>]}


============================== 10:58:42.293523 | 27f55c73-3953-4526-bbb6-175150afafaa ==============================
[0m10:58:42.293523 [info ] [MainThread]: Running with dbt=1.10.13
[0m10:58:42.293806 [debug] [MainThread]: running dbt with arguments {'version_check': 'True', 'indirect_selection': 'eager', 'use_colors': 'True', 'fail_fast': 'False', 'invocation_command': 'dbt deps', 'quiet': 'False', 'cache_selected_only': 'False', 'debug': 'False', 'send_anonymous_usage_stats': 'True', 'printer_width': '80', 'no_print': 'None', 'profiles_dir': '/Users/izakmohamed/.dbt', 'warn_error': 'None', 'static_parser': 'True', 'use_experimental_parser': 'False', 'target_path': 'None', 'introspect': 'True', 'log_path': 'logs', 'empty': 'None', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_cache_events': 'False', 'write_json': 'True', 'log_format': 'default'}
[0m10:58:42.294159 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/izakmohamed/Documents/DEV & CODE/SIMPLON 2025/Formation Intensif/BRIEF/BRIEF 08 Apache Spark/Apache_Spark/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:58:42.315899 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.061883334, "process_in_blocks": "0", "process_kernel_time": 0.120065, "process_mem_max_rss": "106790912", "process_out_blocks": "0", "process_user_time": 0.576204}
[0m10:58:42.316227 [debug] [MainThread]: Command `dbt deps` failed at 10:58:42.316180 after 0.06 seconds
[0m10:58:42.316386 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105767ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059c5910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105721bf0>]}
[0m10:58:42.316529 [debug] [MainThread]: Flushing usage events
[0m10:58:42.772619 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:16:24.608299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b27cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11268f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11268fb10>]}


============================== 09:16:24.610992 | 305785d6-903b-4ef4-8410-502936c3f5f6 ==============================
[0m09:16:24.610992 [info ] [MainThread]: Running with dbt=1.10.13
[0m09:16:24.611259 [debug] [MainThread]: running dbt with arguments {'use_colors': 'True', 'profiles_dir': '/Users/izakmohamed/.dbt', 'target_path': 'None', 'invocation_command': 'dbt run --select analyses', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'warn_error': 'None', 'static_parser': 'True', 'printer_width': '80', 'version_check': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'cache_selected_only': 'False', 'introspect': 'True', 'empty': 'False', 'no_print': 'None', 'write_json': 'True', 'debug': 'False', 'log_format': 'default', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'use_experimental_parser': 'False', 'quiet': 'False'}
[0m09:16:24.611529 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/izakmohamed/Documents/DEV & CODE/SIMPLON 2025/Formation Intensif/BRIEF/BRIEF 08 Apache Spark/Apache_Spark/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:16:24.613014 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.042481624, "process_in_blocks": "0", "process_kernel_time": 0.100432, "process_mem_max_rss": "104677376", "process_out_blocks": "0", "process_user_time": 0.500116}
[0m09:16:24.613215 [debug] [MainThread]: Command `dbt run` failed at 09:16:24.613180 after 0.04 seconds
[0m09:16:24.613346 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112567ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126c9910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112521ae0>]}
[0m09:16:24.613476 [debug] [MainThread]: Flushing usage events
[0m09:16:25.098974 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:42:24.320220 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e27cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11098f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11098fb10>]}


============================== 10:42:24.322978 | 8316bf91-b04e-4d18-9688-f61a86f8845e ==============================
[0m10:42:24.322978 [info ] [MainThread]: Running with dbt=1.10.13
[0m10:42:24.323258 [debug] [MainThread]: running dbt with arguments {'use_colors': 'True', 'invocation_command': 'dbt run --select produits_jeunes_clients.sql', 'no_print': 'None', 'empty': 'False', 'debug': 'False', 'static_parser': 'True', 'introspect': 'True', 'write_json': 'True', 'log_path': 'logs', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'warn_error': 'None', 'log_format': 'default', 'partial_parse': 'True', 'log_cache_events': 'False', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'quiet': 'False', 'fail_fast': 'False', 'version_check': 'True', 'profiles_dir': '/Users/izakmohamed/.dbt', 'cache_selected_only': 'False'}
[0m10:42:24.323532 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/izakmohamed/Documents/DEV & CODE/SIMPLON 2025/Formation Intensif/BRIEF/BRIEF 08 Apache Spark/Apache_Spark/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:42:24.324916 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.041215625, "process_in_blocks": "0", "process_kernel_time": 0.108069, "process_mem_max_rss": "106151936", "process_out_blocks": "0", "process_user_time": 0.535123}
[0m10:42:24.325174 [debug] [MainThread]: Command `dbt run` failed at 10:42:24.325134 after 0.04 seconds
[0m10:42:24.325318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110867ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1109c9910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110821ae0>]}
[0m10:42:24.325449 [debug] [MainThread]: Flushing usage events
[0m10:42:24.817733 [debug] [MainThread]: An error was encountered while trying to flush usage events
